config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'

  get 'pages/authors'

  get 'pages/titles'

  get 'pages/subjects'

  root to: 'pages#home'
  resources :blogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :blog

  def create
    @author = Author.new(author_params)

    if @author.save
      redirect_to @author, notice: "#{@author.name.uppcase} authorized"
    else
      render :new
    end
  end



end

app/models/blog.rb
class Blog < ApplicationRecord
  belongs_to :author

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :get_blog , only: [:show, :edit, :destroy]

  def index
    @blogs = Blog.all.reverse
  end

  def show
  end

  def new
    @blog = Blog.new
  end

  def edit
    @blog = Blog.find(params[:id])
  end

  def destroy
      @blog = Blog.find(params[:id])
      @blog.destroy
      redirect_to blogs_path, notice: 'Blog deleted'
  end

  def create
    @blog = Blog.new(blog_params)
    set_author_id
    if @blog.save
      redirect_to @blog, notice: "#{@blog.title.upcase} added to blogs."
    else
      render :new
    end
  end

  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blog_params)
      redirect_to @blog, notice: "#{@blog.title.upcase} added to blogs."
    else
      render :new
    end
  end

  private

  def get_blog
    @blog = Blog.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:title,
                                 :sub_title,
                                 :subject,
                                 :body,
                                 :author_id)
  end

  def set_author_id 
    # This would include logic in order to set the author_id based on the user that is logged in. since this app does not include this function the author_id will be set to guest (1)
    @blog.author_id = 1 #if @blog.author_id.nil?
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :get_blogs, only: [:titles, :subjects]

  def home
  end

  def authors
    @authors = Author.all
  end

  def titles
  end

  def subjects
  end

  private

  def get_blogs
    @blogs = Blog.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/blogs/edit.html.erb
<h1 class="page_title">Edit Blog</h1>
<hr>

<% blog = @blog %>
<%= form_with(model: blog, local: true) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, id: :blog_title %>
  </div>

  <div class="field">
    <%= f.label :sub_title %>
    <%= f.text_field :sub_title, id: :blog_sub_title %>
  </div>

  <div class="field">
    <%= f.label :subject %>
    <%= f.text_field :subject, id: :blog_subject %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body, id: :blog_body %>
  </div>

<!-- This should be set auto based on the logged in user -->
<!--     <div class="field">
    <%= f.label :author_id %>
    <%= f.text_field :author_id, id: :blog_author_id %>
  </div> -->

  <div class="action">
    <%= f.submit %>
  </div>

  <% end %>

app/views/blogs/index.html.erb
<h1 class="page_title">Blogs</h1>
<hr>
<p><%= link_to 'New Blog Post', new_blog_path %></p>


  <% @blogs.each do |blog| %>
      <div class="blog_div">
        <h1><%= link_to blog.title, blog %></h1>
        <h2><%= blog.sub_title %></h2>
        <h3><%= blog.subject %></h3>
        <p><%= blog.body.slice(0..40) + "...." %></p>
      </div>
  <% end %>

app/views/blogs/new.html.erb
<h1 class="page_title">New blog</h1>
<hr>
<% blog = @blog %>

<%= form_with(model: blog, local: true) do |f| %>
  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, id: :blog_title %>
  </div>

  <div class="field">
    <%= f.label :sub_title %>
    <%= f.text_field :sub_title, id: :blog_sub_title %>
  </div>

  <div class="field">
    <%= f.label :subject %>
    <%= f.text_field :subject, id: :blog_subject %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body, id: :blog_body %>
  </div>

<!-- This should be set auto based on the logged in user -->
<!--     <div class="field">
    <%= f.label :author_id %>
    <%= f.text_field :author_id, id: :blog_author_id %>
  </div> -->

  <div class="action">
    <%= f.submit %>
  </div>

<% end %>

app/views/blogs/show.html.erb
<h1 class="page_title"><%= @blog.title %></h1>
<hr>
<p><em>by <%= @blog.author.name %></em></p>

<div id="show_blog_div">
  <div>
    <h2><%= @blog.sub_title %></h2>
    <h4><em>-<%= @blog.subject %></em></h4>
  </div>
  <p><%= @blog.body %></p>
  <%= link_to "Edit", edit_blog_path(@blog) %>
  <%= link_to "Delete", blog_path(@blog), method: :delete, data: {confirm: 'are you sure you want to delete this blog?'} %>
<div>
  <%= link_to 'Back to blogs', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bloggard</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/pages/authors.html.erb
<h1  class="page_title">Authors</h1>
<hr>

<% @authors.each do |auth| %>
  <div class="author_div">
    <div class="author_head_div">
      <div><%= auth.name %></div>
      <div><span>-<%= "Blogs: #{auth.blog.count}" %></span></div>
    </div>
    <div>
      <% auth.blog.each do |blog| %>
        <div class="title_div"><%= link_to blog.title, blog %></div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/pages/home.html.erb
<h1 class="page_title">Home</h1>
<hr>

<div id="home_links">
  
  <div><%= link_to 'Blogs', blogs_path %></div>
  <div><%= link_to 'Authors', pages_authors_path %></div>
  <div><%= link_to 'Subjects', pages_subjects_path %></div>
  <div><%= link_to 'Titles', pages_titles_path %></div>

</div>

app/views/pages/subjects.html.erb
<h1 class="page_title">Subjects</h1>
<hr>
<div>
<% @blogs.sort_by {|b| b.subject}.each do |blog| %>
  <div class="title_item"><%= link_to blog.subject, blog%></div>
<% end %>
</div>

app/views/pages/titles.html.erb
<h1 class="page_title">Titles</h1>
<hr>

<% @blogs.sort_by {|b| b.title}.each do |blog| %>
  <div class="title_item"><%= link_to blog.title, blog %></div>
<% end %>

app/views/shared/_header.html.erb
      <div class="header_spacer"></div>

  <div class="header_frame">
    <div>
      <div>Bloggard <span><em>blogs that don't make sense!</em></span></div>
      <ul>
        <%= link_to 'Home', root_path %>
        <%= link_to 'Blogs', blogs_path %>
        <%= link_to 'Authors', pages_authors_path %>
        <%= link_to 'Subjects', pages_subjects_path %>
        <%= link_to 'Titles', pages_titles_path %>
      </ul>
    </div>
  </div>